#! /bin/sh -

vagrant up --no-provision
# vagrant provision --provision-with install-ports
vagrant provision --provision-with install-ports-tools
vagrant provision --provision-with install-utilities
vagrant provision --provision-with configure-environment
