Vagrant.configure("2") do |config|
  config.vm.define "workshop-machine" do |host|
    host.vm.box = "bento/freebsd-11.1"
    host.vm.hostname = "workshop-machine"
    host.ssh.shell = "sh"

    host.vm.synced_folder ".", "/vagrant", type: "rsync"

    host.vm.provision "install-ports", type: "shell", privileged: true, path: "./provisions/install-ports.sh"
    host.vm.provision "install-ports-tools", type: "shell", path: "./provisions/install-ports-tools.sh"
    host.vm.provision "install-utilities", type: "shell", path: "./provisions/install-utilities.sh"
    host.vm.provision "configure-environment", type: "shell", path: "./provisions/configure-environment.sh"

    host.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.name = "workshop-machine"
      vb.cpus = 2
      vb.memory = 2048
    end
  end
end

# vim: filetype=ruby softtabstop=2 shiftwidth=2 tabstop=2 expandtab:
